using Microsoft.AspNetCore.Mvc.Rendering;

namespace StageApp.ViewModels
{
    public class CreateNetworkViewModel
    {
        public string? OrganizationId { get; set; }
        public string? Name { get; set; }
        public List<string> SelectedNetworkTypes { get; set; } = new List<string>();
        public string? Timezone { get; set; }
        public IEnumerable<SelectListItem> Organizations { get; set; } = new List<SelectListItem>();

        public IEnumerable<SelectListItem> NetworkTypes = new List<SelectListItem>
        {
            new SelectListItem("Appliance", "appliance"), 
            new SelectListItem("Switch", "switch"),  
            new SelectListItem("Sensor", "sensor"),
            new SelectListItem("Wireless", "wireless"), 
            new SelectListItem("Camera", "camera"),
            new SelectListItem("EMM (Systems manager)", "systemsManager"),
            new SelectListItem("Cellular gateway", "cellularGateway"),
            new SelectListItem("Wireless LAN controller", "wirelessController")
        };
        public IEnumerable<SelectListItem> Timezones = new List<SelectListItem>
        {
            new SelectListItem { Text = "Europe - Amsterdam (UTC + 1.0)", Value = "Europe/Amsterdam" },
            new SelectListItem { Text = "US - Eastern (UTC -5.0)", Value = "US/Eastern" },
            new SelectListItem { Text = "US - Central (UTC -6.0)", Value = "US/Central" },
            new SelectListItem { Text = "US - Arizona (UTC -7.0)", Value = "US/Arizona" },
            new SelectListItem { Text = "US - Mountain (UTC -7.0)", Value = "US/Mountain" },
            new SelectListItem { Text = "US - Pacific (UTC -8.0)", Value = "US/Pacific" },
            new SelectListItem { Text = "US - Alaska (UTC -9.0)", Value = "US/Alaska" },
            new SelectListItem { Text = "US - Aleutian (UTC -10.0)", Value = "US/Aleutian" },
            new SelectListItem { Text = "US - Hawaii (UTC -10.0)", Value = "US/Hawaii" },
            new SelectListItem { Text = "US - Samoa (UTC -11.0)", Value = "US/Samoa" },
            new SelectListItem { Text = "Canada - Newfoundland (UTC -3.5)", Value = "Canada/Newfoundland" },
            new SelectListItem { Text = "Canada - Atlantic (UTC -4.0)", Value = "Canada/Atlantic)" },
            new SelectListItem { Text = "Canada - Eastern (UTC -5.0)", Value = "Canada/Eastern" },
            new SelectListItem { Text = "Canada - Central (UTC -6.0)", Value = "Canada/Central" },
            new SelectListItem { Text = "Canada - Saskatchewan (UTC -6.0)", Value = "Canada/Saskatchewan" },
            new SelectListItem { Text = "Canada - Mountain (UTC -7.0)", Value = "Canada/Mountain" },
            new SelectListItem { Text = "Canada - Yukon (UTC -7.0)", Value = "Canada/Yukon" },
            new SelectListItem { Text = "Canada - Pacific (UTC -8.0)", Value = "Canada/Pacific" },
            new SelectListItem { Text = "Europe - Moscow (UTC +3.0)", Value = "Europe/Moscow" },
            new SelectListItem { Text = "Europe - Istanbul (UTC +3.0)", Value = "Europe/Istanbul)" },
            new SelectListItem { Text = "Europe - Helsinki (UTC +2.0)", Value = "Europe/Helsinki" },
            new SelectListItem { Text = "Europe - Athens (UTC +2.0)", Value = "Europe/Athens" },
            new SelectListItem { Text = "Europe - Vienna (UTC +1.0)", Value = "Europe/Vienna" },
            new SelectListItem { Text = "Europe - Brussels (UTC + 1.0)", Value = "Europe/Brussels" },
            new SelectListItem { Text = "Europe - Zurich (UTC + 1.0)", Value = "Europe/Zurich" },
            new SelectListItem { Text = "Europe - Prague (UTC + 1.0)", Value = "Europe/Prague" },
            new SelectListItem { Text = "Europe - Berlin (UTC + 1.0)", Value = "Europe/Berlin" },
            new SelectListItem { Text = "Europe - Madrid (UTC + 1.0)", Value = "Europe/Madrid" },
            new SelectListItem { Text = "Europe - Paris (UTC + 1.0)", Value = "Europe/Paris" },
            new SelectListItem { Text = "Europe - Budapest (UTC + 1.0)", Value = "Europe/Budapest" },
            new SelectListItem { Text = "Europe - Rome (UTC + 1.0)", Value = "Europe/Rome" },
            new SelectListItem { Text = "Europe - Warsaw (UTC + 1.0)", Value = "Europe/Warsaw" },
            new SelectListItem { Text = "Europe - London (UTC + 0.0)", Value = "Europe/London" },
            new SelectListItem { Text = "Europe - Dublin (UTC +0.0)", Value = "Europe/Dublin" },
            new SelectListItem { Text = "Europe - Lisbon (UTC + 0.0)", Value = "Europe/Lisbon" },
            new SelectListItem { Text = "Pacific - Kiritimati (UTC + 14.0) ", Value = "Pacific/Kiritimati" },
            new SelectListItem { Text = "Pacific - Chatham (UTC + 13.75)", Value = "Pacific/Chatham" },
            new SelectListItem { Text = "Antarctica - McMurdo (UTC + 13.0)", Value = "Antarctica/McMurdo" },
            new SelectListItem { Text = "Antarctica - South Pole (UTC + 13.0) ", Value = "Antarctica/South Pole" },
            new SelectListItem { Text = "Pacific - Enderbury (UTC + 13.0)", Value = "Pacific/Enderbury" },
            new SelectListItem { Text = "Pacific - Auckland (UTC + 13.0)", Value = "Pacific/Auckland" },
            new SelectListItem { Text = "Pacific - Kanton (UTC + 13.0)", Value = "Pacific/Kanton" },
            new SelectListItem { Text = "Pacific - Fakaofo (UTC + 13.0)", Value = "Pacific/Fakaofo" },
            new SelectListItem { Text = "Pacific - Tongatapu (UTC + 13.0)", Value = "Pacific/Tongatapu" },
            new SelectListItem { Text = "Pacific - Apia (UTC + 13.0)", Value = "Pacific/Apia" },
            new SelectListItem { Text = "Pacific - Funafuti (UTC + 12.0)", Value = "Pacific/Funafuti" },
            new SelectListItem { Text = "Pacific - Majuro (UTC + 12.0)", Value = "Pacific/Majuro" },
            new SelectListItem { Text = "Pacific - Wake (UTC +12.0)", Value = "Pacific/Wake" },
            new SelectListItem { Text = "Pacific - Wallis (UTC + 12.0)", Value = "Pacific/Wallis" },
            new SelectListItem { Text = "Pacific - Fiji (UTC + 12.0)", Value = "Pacific/Fiji" },
            new SelectListItem { Text = "Pacific - Tarawa (UTC + 12.0)", Value = "Pacific/Tarawa" },
            new SelectListItem { Text = "Pacific - Kwajalein (UTC + 12.0)", Value = "Pacific/Kwajalein" },
            new SelectListItem { Text = "Pacific - Norfolk (UTC + 12.0)", Value = "Pacific/Norfolk" },
            new SelectListItem { Text = "Pacific - Nauru (UTC + 12.0)", Value = "Pacific/Nauru" },
            new SelectListItem { Text = "Asia - Kamchatka (UTC + 12.0)", Value = "Asia/Kamchatka" },
            new SelectListItem { Text = "Asia - Anadyr (UTC + 12.0)", Value = "Asia/Anadyr" },
            new SelectListItem { Text = "Australia - ACT (UTC + 11.0)", Value = "Australia/ACT" },
            new SelectListItem { Text = "Australia - Canberra (UTC + 11.0)", Value = "Australia/Canberra" },
            new SelectListItem { Text = "Australia - Currie (UTC + 11.0)", Value = "Australia/Currie" },
            new SelectListItem { Text = "Australia - LHI (UTC + 11.0)", Value = "Australia/LHI" },
            new SelectListItem { Text = "Australia - NSW (UTC + 11.0)", Value = "Australia/NSW" },
            new SelectListItem { Text = "Australia - Tasmania (UTC + 11.0)", Value = "Australia/Tasmania" },
            new SelectListItem { Text = "Australia - Victoria (UTC + 11.0)", Value = "Australia/Victoria" },
            new SelectListItem { Text = "Pacific - Pohnpei (UTC + 11.0)", Value = "Pacific/Pohnpei" },
            new SelectListItem { Text = "Pacific - Ponape (UTC + 11.0)", Value = "Pacific/Ponape" },
            new SelectListItem { Text = "Antarctica - Casey (UTC + 11.0)", Value = "Antarctica/Casey" },
            new SelectListItem { Text = "Australia - Lord Howe (UTC + 11.0)", Value = "Australia/Lord Howe" },
            new SelectListItem { Text = "Antarctica - Macquarie (UTC + 11.0)", Value = "Antarctica/Macquarie" },
            new SelectListItem { Text = "Australia - Hobart (UTC + 11.0)", Value = "Australia/Hobart" },
            new SelectListItem { Text = "Australia - Melbourne (UTC + 11.0)", Value = "Australia/Melbourne" },
            new SelectListItem { Text = "Australia - Sydney (UTC + 11.0)", Value = "Australia/Sydney" },
            new SelectListItem { Text = "Pacific - Kosrae (UTC + 11.0)", Value = "Pacific/Kosrae" },
            new SelectListItem { Text = "Pacific - Guadalcanal (UTC + 11.0)", Value = "Pacific/Guadalcanal" },
            new SelectListItem { Text = "Pacific - Noumea (UTC + 11.0)", Value = "Pacific/Noumea" },
            new SelectListItem { Text = "Pacific - Bougainville (UTC + 11.0)", Value = "Pacific/Bougainville" },
            new SelectListItem { Text = "Asia - Magadan (UTC + 11.0)", Value = "Asia/Magadan" },
            new SelectListItem { Text = "Asia - Sakhalin (UTC + 11.0)", Value = "Asia/Sakhalin" },
            new SelectListItem { Text = "Asia - Srednekolymsk (UTC + 11.0)", Value = "Asia/Srednekolymsk" },
            new SelectListItem { Text = "Pacific - Efate (UTC + 11.0)", Value = "Pacific/Efate" },
            new SelectListItem { Text = "Australia - South (UTC + 10.5)", Value = "Australia/South" },
            new SelectListItem { Text = "Australia - Yancowinna (UTC + 10.5)", Value = "Australia/Yancowinna" },
            new SelectListItem { Text = "Australia - Broken Hill (UTC + 10.5)", Value = "Australia/Broken Hill" },
            new SelectListItem { Text = "Australia - Adelaide (UTC + 10.5)", Value = "Australia/Adelaide" },
            new SelectListItem { Text = "Antarctica - Dumont D’Urville (UTC + 10.0)", Value = "Antarctica/Dumont D’Urville" },
            new SelectListItem { Text = "Australia - Queensland (UTC + 10.0)", Value = "Australia/Queensland" },
            new SelectListItem { Text = "Pacific - Chuuk (UTC + 10.0)", Value = "Pacific/Chuuk" },
            new SelectListItem { Text = "Pacific - Saipan (UTC + 10.0)", Value = "Pacific/Saipan" },
            new SelectListItem { Text = "Pacific - Truk (UTC + 10.0)", Value = "Pacific/Truk" },
            new SelectListItem { Text = "Pacific - Yap (UTC + 10.0)", Value = "Pacific/Yap" },
            new SelectListItem { Text = "Pacific - Port Moresby (UTC + 10.0)", Value = "Pacific/Port Moresby" },
            new SelectListItem { Text = "Australia - Brisbane (UTC + 10.0)", Value = "Australia/Brisbane" },
            new SelectListItem { Text = "Australia - Lindeman (UTC + 10.0)", Value = "Australia/Lindeman" },
            new SelectListItem { Text = "Pacific - Guam (UTC + 10.0)", Value = "Pacific/Guam" },
            new SelectListItem { Text = "Asia - Vladivostok (UTC + 10.0)", Value = "Asia/Vladivostok" },
            new SelectListItem { Text = "Asia - Ust-Nera (UTC + 10.0)", Value = "Asia/Ust-Nera" },
            new SelectListItem { Text = "Australia - North (UTC + 9.5)", Value = "Australia/North" },
            new SelectListItem { Text = "Australia - Darwin (UTC + 9.5)", Value = "Australia/Darwin" },
            new SelectListItem { Text = "Japan (UTC + 9.0)", Value = "Japan" },
            new SelectListItem { Text = "Asia - Jayapura (UTC + 9.0)", Value = "Asia/Jayapura" },
            new SelectListItem { Text = "Asia - Tokyo (UTC + 9.0)", Value = "Asia/Tokyo" },
            new SelectListItem { Text = "Asia - Pyongyang (UTC + 9.0)", Value = "Asia/Pyongyang" },
            new SelectListItem { Text = "Asia - Seoul (UTC + 9.0)", Value = "Asia/Seoul" },
            new SelectListItem { Text = "Pacific - Palau (UTC + 9.0)", Value = "Pacific/Palau" },
            new SelectListItem { Text = "Asia - Chita (UTC + 9.0)", Value = "Asia/Chita" },
            new SelectListItem { Text = "Asia - Yakutsk (UTC + 9.0)", Value = "Asia/Yakutsk" },
            new SelectListItem { Text = "Asia - Khandyga (UTC + 9.0)", Value = "Asia/Khandyga" },
            new SelectListItem { Text = "Asia - Dili (UTC + 9.0)", Value = "Asia/Dili" },
            new SelectListItem { Text = "Australia - Eucla (UTC + 8.75)", Value = "Australia/Eucla" },
            new SelectListItem { Text = "Asia - Brunei (UTC + 8.0)", Value = "Asia/Brunei" },
            new SelectListItem { Text = "Asia - Chongqing (UTC + 8.0)", Value = "Asia/Chongqing" },
            new SelectListItem { Text = "Asia - Chungking (UTC + 8.0)", Value = "Asia/Chungking" },
            new SelectListItem { Text = "Asia - Harbin (UTC + 8.0)", Value = "Asia/Harbin" },
            new SelectListItem { Text = "Asia - Kuala Lumpur (UTC + 8.0)", Value = "Asia/Kuala Lumpur" },
            new SelectListItem { Text = "Asia - Macao (UTC + 8.0)", Value = "Asia/Macao" },
            new SelectListItem { Text = "Asia - Ujung Pandang (UTC + 8.0)", Value = "Asia/Ujung Pandang" },
            new SelectListItem { Text = "Asia - Ulan Bator (UTC + 8.0)", Value = "Asia/Ulan Bator" },
            new SelectListItem { Text = "Australia - West (UTC + 8.0)", Value = "Australia/West" },
            new SelectListItem { Text = "Hongkong (UTC + 8.0)", Value = "Hongkong" },
            new SelectListItem { Text = "Singapore (UTC + 8.0)", Value = "Singapore" },
            new SelectListItem { Text = "Australia - Perth (UTC + 8.0)", Value = "Australia/Perth" },
            new SelectListItem { Text = "Asia - Kuching (UTC + 8.0)", Value = "Asia/Kuching" },
            new SelectListItem { Text = "Asia - Shanghai (UTC + 8.0)", Value = "Asia/Shanghai" },
            new SelectListItem { Text = "Asia - Hong Kong (UTC + 8.0)", Value = "(Asia/Hong Kong" },
            new SelectListItem { Text = "Asia - Makassar (UTC + 8.0)", Value = "Asia/Makassar" },
            new SelectListItem { Text = "Asia - Ulaanbaatar (UTC + 8.0)", Value = "Asia/Ulaanbaatar" },
            new SelectListItem { Text = "Asia - Choibalsan (UTC + 8.0)", Value = "Asia/Choibalsan" },
            new SelectListItem { Text = "Asia - Macau (UTC + 8.0)", Value = "Asia/Macau" },
            new SelectListItem { Text = "Asia - Singapore (UTC + 8.0)", Value = "Asia/Singapore" },
            new SelectListItem { Text = "Asia - Manila (UTC + 8.0)", Value = "Asia/Manila" },
            new SelectListItem { Text = "Asia - Irkutsk (UTC + 8.0)", Value = "Asia/Irkutsk" },
            new SelectListItem { Text = "Asia - Taipei (UTC + 8.0)", Value = "Asia/Taipei" },
            new SelectListItem { Text = "Asia - Phnom Penh (UTC + 7.0)", Value = "Asia/Phnom Penh" },
            new SelectListItem { Text = "Asia - Saigon (UTC + 7.0)", Value = "Asia/Saigon" },
            new SelectListItem { Text = "Asia - Vientiane (UTC + 7.0)", Value = "Asia/Vientiane" },
            new SelectListItem { Text = "Indian - Christmas (UTC + 7.0)", Value = "Indian/Christmas" },
            new SelectListItem { Text = "Antarctica - Davis (UTC + 7.0)", Value = "Antarctica/Davis" },
            new SelectListItem { Text = "Asia - Bangkok (UTC +7.0)", Value = "Asia/Bangkok" },
            new SelectListItem { Text = "Asia - Jakarta (UTC + 7.0)", Value = "Asia/Jakarta" },
            new SelectListItem { Text = "Asia - Pontianak (UTC + 7.0)", Value = "Asia/Pontianak" },
            new SelectListItem { Text = "Asia - Hovd (UTC + 7.0)", Value = "Asia/Hovd" },
            new SelectListItem { Text = "Asia - Novosibirsk (UTC + 7.0)", Value = "Asia/Novosibirsk" },
            new SelectListItem { Text = "Asia - Barnaul (UTC + 7.0)", Value = "Asia/Barnaul" },
            new SelectListItem { Text = "Asia - Tomsk (UTC + 7.0)", Value = "Asia/Tomsk" },
            new SelectListItem { Text = "Asia - Novokuznetsk (UTC + 7.0)", Value = "Asia/Novokuznetsk" },
            new SelectListItem { Text = "Asia - Krasnoyarsk (UTC + 7.0)", Value = "Asia/Krasnoyarsk" },
            new SelectListItem { Text = "Asia - Ho Chi Minh (UTC + 7.0)", Value = "Asia/Ho Chi Minh" },
            new SelectListItem { Text = "Asia - Rangoon (UTC + 6.5)", Value = "Asia/Rangoon" },
            new SelectListItem { Text = "Indian - Cocos (UTC + 6.5)", Value = "Indian/Cocos" },
            new SelectListItem { Text = "Asia - Yangon (UTC + 6.5)", Value = "Asia/Yangon" },
            new SelectListItem { Text = "Antarctica - Vostok (UTC + 6.0)", Value = "Antarctica/Vostok" },
            new SelectListItem { Text = "Asia - Dacca (UTC + 6.0)", Value = "Asia/Dacca" },
            new SelectListItem { Text = "Asia - Kashgar (UTC + 6.0)", Value = "Asia/Kashgar" },
            new SelectListItem { Text = "Asia - Thimbu (UTC + 6.0)", Value = "Asia/Thimbu" },
            new SelectListItem { Text = "Asia - Urumqi (UTC + 6.0)", Value = "Asia/Urumqi" },
            new SelectListItem { Text = "Asia - Dhaka (UTC + 6.0)", Value = "Asia/Dhaka" },
            new SelectListItem { Text = "Asia - Thimphu (UTC + 6.0)", Value = "Asia/Thimphu" },
            new SelectListItem { Text = "Indian - Chagos (UTC + 6.0)", Value = "Indian/Chagos" },
            new SelectListItem { Text = "Asia - Bishkek (UTC + 6.0)", Value = "Asia/Bishkek" },
            new SelectListItem { Text = "Asia - Almaty (UTC +6.0)", Value = "Asia/Almaty" },
            new SelectListItem { Text = "Asia - Qostanay (UTC + 6.0)", Value = "Asia/Qostanay" },
            new SelectListItem { Text = "Asia - Omsk (UTC + 6.0)", Value = "Asia/Omsk" },
            new SelectListItem { Text = "Asia - Katmandu (UTC +5.75)", Value = "Asia/Katmandu" },
            new SelectListItem { Text = "Asia - Kathmandu (UTC + 5.75)", Value = "Asia/Kathmandu" },
            new SelectListItem { Text = "Asia - Calcutta (UTC + 5.5)", Value = "Asia/Calcutta" },
            new SelectListItem { Text = "Asia - Kolkata (UTC + 5.5)", Value = "Asia/Kolkata" },
            new SelectListItem { Text = "Asia - Colombo (UTC + 5.5)", Value = "Asia/Colombo" },
            new SelectListItem { Text = "Asia - Ashkhabad (UTC + 5.0)", Value = "Asia/Ashkhabad" },
            new SelectListItem { Text = "Indian - Kerguelen (UTC + 5.0)", Value = "Indian/Kerguelen" },
            new SelectListItem { Text = "Antarctica - Mawson (UTC + 5.0)", Value = "Antarctica/Mawson" },
            new SelectListItem { Text = "Asia - Qyzylorda (UTC + 5.0)", Value = "Asia/Qyzylorda" },
            new SelectListItem { Text = "Asia - Aqtobe (UTC + 5.0)", Value = "Asia/Aqtobe" },
            new SelectListItem { Text = "Asia - Aqtau (UTC + 5.0)", Value = "Asia/Aqtau" },
            new SelectListItem { Text = "Asia - Atyrau (UTC + 5.0)", Value = "Asia/Atyrau" },
            new SelectListItem { Text = "Asia - Oral (UTC + 5.0)", Value = "Asia/Oral" },
            new SelectListItem { Text = "Indian - Maldives (UTC + 5.0)", Value = "Indian/Maldives" },
            new SelectListItem { Text = "Asia - Karachi (UTC + 5.0)", Value = "Asia/Karachi" },
            new SelectListItem { Text = "Asia - Yekaterinburg (UTC + 5.0)", Value = "Asia/Yekaterinburg" },
            new SelectListItem { Text = "Asia - Dushanbe (UTC + 5.0)", Value = "Asia/Dushanbe" },
            new SelectListItem { Text = "Asia - Ashgabat (UTC + 5.0)", Value = "Asia/Ashgabat" },
            new SelectListItem { Text = "Asia - Samarkand (UTC + 5.0)", Value = "Asia/Samarkand" },
            new SelectListItem { Text = "Asia - Tashkent (UTC + 5.0)", Value = "Asia/Tashkent" },
            new SelectListItem { Text = "Asia - Kabul (UTC + 4.5)", Value = "Asia/Kabul" },
            new SelectListItem { Text = "Asia - Muscat (UTC + 4.0)", Value = "Asia/Muscat" },
            new SelectListItem { Text = "Indian - Mahe (UTC + 4.0)", Value = "Indian/Mahe" },
            new SelectListItem { Text = "Indian - Reunion (UTC + 4.0)", Value = "Indian/Reunion" },
            new SelectListItem { Text = "Asia - Dubai (UTC + 4.0)", Value = "Asia/Dubai" },
            new SelectListItem { Text = "Asia - Yerevan (UTC + 4.0)", Value = "Asia/Yerevan" },
            new SelectListItem { Text = "Asia - Baku (UTC + 4.0)", Value = "Asia/Baku" },
            new SelectListItem { Text = "Asia - Tbilisi (UTC + 4.0)", Value = "Asia/Tbilisi" },
            new SelectListItem { Text = "Indian - Mauritius (UTC + 4.0)", Value = "Indian/Mauritius" },
            new SelectListItem { Text = "Europe - Astrakhan (UTC + 4.0)", Value = "Europe/Astrakhan" },
            new SelectListItem { Text = "Europe - Saratov (UTC + 4.0)", Value = "Europe/Saratov" },
            new SelectListItem { Text = "Europe - Ulyanovsk (UTC + 4.0)", Value = "Europe/Ulyanovsk" },
            new SelectListItem { Text = "Europe - Samara (UTC + 4.0)", Value = "Europe/Samara" },
            new SelectListItem { Text = "Iran (UTC + 3.5)", Value = "Iran" },
            new SelectListItem { Text = "Asia - Tehran (UTC + 3.5)", Value = "Asia/Tehran" },
            new SelectListItem { Text = "Africa - Addis Ababa (UTC + 3.0)", Value = "Africa/Addis Ababa" },
            new SelectListItem { Text = "Africa - Asmara (UTC + 3.0)", Value = "Africa/Asmara" },
            new SelectListItem { Text = "Africa - Asmera (UTC + 3.0)", Value = "Africa/Asmera" },
            new SelectListItem { Text = "Africa - Dar es Salaam (UTC + 3.0)", Value = "Africa/Dar es Salaam" },
            new SelectListItem { Text = "Africa - Djibouti (UTC + 3.0)", Value = "Africa/Djibouti" },
            new SelectListItem { Text = "Africa - Kampala (UTC + 3.0)", Value = "Africa/Kampala" },
            new SelectListItem { Text = "Africa - Mogadishu (UTC + 3.0)", Value = "Africa/Mogadishu" },
            new SelectListItem { Text = "Antarctica - Syowa (UTC + 3.0)", Value = "Antarctica/Syowa" },
            new SelectListItem { Text = "Asia - Aden (UTC + 3.0)", Value = "Asia/Aden" },
            new SelectListItem { Text = "Asia - Bahrain (UTC + 3.0)", Value = "Asia/Bahrain" },
            new SelectListItem { Text = "Asia - Istanbul (UTC + 3.0)", Value = "Asia/Istanbul" },
            new SelectListItem { Text = "Asia - Kuwait (UTC + 3.0)", Value = "Asia/Kuwait" },
            new SelectListItem { Text = "Indian - Antananarivo (UTC + 3.0)", Value = "Indian/Antananarivo" },
            new SelectListItem { Text = "Indian - Comoro (UTC + 3.0)", Value = "Indian/Comoro" },
            new SelectListItem { Text = "Indian - Mayotte (UTC + 3.0)", Value = "Indian/Mayotte" },
            new SelectListItem { Text = "Turkey (UTC + 3.0)", Value = "Turkey" },
            new SelectListItem { Text = "Asia - Riyadh (UTC + 3.0)", Value = "(Asia/Riyadh" },
            new SelectListItem { Text = "Asia - Qatar (UTC + 3.0)", Value = "Asia/Qatar" },
            new SelectListItem { Text = "Europe - Minsk (UTC + 3.0)", Value = "Europe/Minsk" },
            new SelectListItem { Text = "Africa - Nairobi (UTC + 3.0)", Value = "Africa/Nairobi" },
            new SelectListItem { Text = "Asia - Baghdad (UTC + 3.0)", Value = "Asia/Baghdad" },
            new SelectListItem { Text = "Asia - Amman (UTC + 3.0)", Value = "(Asia/Amman" },
            new SelectListItem { Text = "Europe - Simferopol (UTC + 3.0)", Value = "Europe/Simferopol" },
            new SelectListItem { Text = "Europe - Kirov (UTC + 3.0)", Value = "Europe/Kirov" },
            new SelectListItem { Text = "Europe - Volgograd (UTC + 3.0)", Value = "Europe/Volgograd" },
            new SelectListItem { Text = "Asia - Damascus (UTC + 3.0)", Value = "Asia/Damascus" },
            new SelectListItem { Text = "Africa - Blantyre (UTC + 2.0)", Value = "Africa/Blantyre" },
            new SelectListItem { Text = "Africa - Bujumbura (UTC + 2.0)", Value = "Africa/Bujumbura" },
            new SelectListItem { Text = "Africa - Gaborone (UTC +2.0)", Value = "Africa/Gaborone" },
            new SelectListItem { Text = "Africa - Harare (UTC + 2.0)", Value = "Africa/Harare" },
            new SelectListItem { Text = "Africa - Kigali (UTC + 2.0)", Value = "Africa/Kigali" },
            new SelectListItem { Text = "Africa - Lubumbashi (UTC + 2.0)", Value = "Africa/Lubumbashi" },
            new SelectListItem { Text = "Africa - Lusaka (UTC + 2.0)", Value = "Africa/Lusaka" },
            new SelectListItem { Text = "Africa - Maseru (UTC + 2.0)", Value = "Africa/Maseru" },
            new SelectListItem { Text = "Africa - Mbabane (UTC + 2.0)", Value = "Africa/Mbabane" }
        };

    }
}
