using Microsoft.AspNetCore.Mvc.Rendering;

namespace StageApp.ViewModels
{
    public class CreateNetworkViewModel
    {
        public string? OrganizationId { get; set; }
        public string? Name { get; set; }
        public List<string> SelectedNetworkTypes { get; set; } = new List<string>();
        public string? Timezone { get; set; }
        public IEnumerable<SelectListItem> Organizations { get; set; } = new List<SelectListItem>();

        public IEnumerable<SelectListItem> NetworkTypes = new List<SelectListItem>
        {
            new SelectListItem("Appliance", "appliance"), 
            new SelectListItem("Switch", "switch"),  
            new SelectListItem("Sensor", "sensor"),
            new SelectListItem("Wireless", "wireless"), 
            new SelectListItem("Camera", "camera"),
            new SelectListItem("EMM (Systems manager)", "systemsManager"),
            new SelectListItem("Cellular gateway", "cellularGateway"),
            new SelectListItem("Wireless LAN controller", "wirelessController")
        };
        public IEnumerable<SelectListItem> Timezones = new List<SelectListItem>
        {
            new SelectListItem { Text = "Europe - Amsterdam (UTC + 1.0)", Value = "Europe/Amsterdam" },
            new SelectListItem { Text = "US - Eastern (UTC -5.0)", Value = "US/Eastern" },
            new SelectListItem { Text = "US - Central (UTC -6.0)", Value = "US/Central" },
            new SelectListItem { Text = "US - Arizona (UTC -7.0)", Value = "US/Arizona" },
            new SelectListItem { Text = "US - Mountain (UTC -7.0)", Value = "US/Mountain" },
            new SelectListItem { Text = "US - Pacific (UTC -8.0)", Value = "US/Pacific" },
            new SelectListItem { Text = "US - Alaska (UTC -9.0)", Value = "US/Alaska" },
            new SelectListItem { Text = "US - Aleutian (UTC -10.0)", Value = "US/Aleutian" },
            new SelectListItem { Text = "US - Hawaii (UTC -10.0)", Value = "US/Hawaii" },
            new SelectListItem { Text = "US - Samoa (UTC -11.0)", Value = "US/Samoa" },
            new SelectListItem { Text = "Canada - Newfoundland (UTC -3.5)", Value = "Canada/Newfoundland" },
            new SelectListItem { Text = "Canada - Atlantic (UTC -4.0)", Value = "Canada/Atlantic)" },
            new SelectListItem { Text = "Canada - Eastern (UTC -5.0)", Value = "Canada/Eastern" },
            new SelectListItem { Text = "Canada - Central (UTC -6.0)", Value = "Canada/Central" },
            new SelectListItem { Text = "Canada - Saskatchewan (UTC -6.0)", Value = "Canada/Saskatchewan" },
            new SelectListItem { Text = "Canada - Mountain (UTC -7.0)", Value = "Canada/Mountain" },
            new SelectListItem { Text = "Canada - Yukon (UTC -7.0)", Value = "Canada/Yukon" },
            new SelectListItem { Text = "Canada - Pacific (UTC -8.0)", Value = "Canada/Pacific" },
            new SelectListItem { Text = "Europe - Moscow (UTC +3.0)", Value = "Europe/Moscow" },
            new SelectListItem { Text = "Europe - Istanbul (UTC +3.0)", Value = "Europe/Istanbul)" },
            new SelectListItem { Text = "Europe - Helsinki (UTC +2.0)", Value = "Europe/Helsinki" },
            new SelectListItem { Text = "Europe - Athens (UTC +2.0)", Value = "Europe/Athens" },
            new SelectListItem { Text = "Europe - Vienna (UTC +1.0)", Value = "Europe/Vienna" },
            new SelectListItem { Text = "Europe - Brussels (UTC + 1.0)", Value = "Europe/Brussels" },
            new SelectListItem { Text = "Europe - Zurich (UTC + 1.0)", Value = "Europe/Zurich" },
            new SelectListItem { Text = "Europe - Prague (UTC + 1.0)", Value = "Europe/Prague" },
            new SelectListItem { Text = "Europe - Berlin (UTC + 1.0)", Value = "Europe/Berlin" },
            new SelectListItem { Text = "Europe - Madrid (UTC + 1.0)", Value = "Europe/Madrid" },
            new SelectListItem { Text = "Europe - Paris (UTC + 1.0)", Value = "Europe/Paris" },
            new SelectListItem { Text = "Europe - Budapest (UTC + 1.0)", Value = "Europe/Budapest" },
            new SelectListItem { Text = "Europe - Rome (UTC + 1.0)", Value = "Europe/Rome" },
            new SelectListItem { Text = "Europe - Warsaw (UTC + 1.0)", Value = "Europe/Warsaw" },
            new SelectListItem { Text = "Europe - London (UTC + 0.0)", Value = "Europe/London" },
            new SelectListItem { Text = "Europe - Dublin (UTC +0.0)", Value = "Europe/Dublin" },
            new SelectListItem { Text = "Europe - Lisbon (UTC + 0.0)", Value = "Europe/Lisbon" },
            new SelectListItem { Text = "Pacific - Kiritimati (UTC + 14.0) ", Value = "Pacific/Kiritimati" },
            new SelectListItem { Text = "Pacific - Chatham (UTC + 13.75)", Value = "Pacific/Chatham" },
            new SelectListItem { Text = "Antarctica - McMurdo (UTC + 13.0)", Value = "Antarctica/McMurdo" },
            new SelectListItem { Text = "Antarctica - South Pole (UTC + 13.0) ", Value = "Antarctica/South Pole" },
            new SelectListItem { Text = "Pacific - Enderbury (UTC + 13.0)", Value = "Pacific/Enderbury" },
            new SelectListItem { Text = "Pacific - Auckland (UTC + 13.0)", Value = "Pacific/Auckland" },
            new SelectListItem { Text = "Pacific - Kanton (UTC + 13.0)", Value = "Pacific/Kanton" },
            new SelectListItem { Text = "Pacific - Fakaofo (UTC + 13.0)", Value = "Pacific/Fakaofo" },
            new SelectListItem { Text = "Pacific - Tongatapu (UTC + 13.0)", Value = "Pacific/Tongatapu" },
            new SelectListItem { Text = "Pacific - Apia (UTC + 13.0)", Value = "Pacific/Apia" },
            new SelectListItem { Text = "Pacific - Funafuti (UTC + 12.0)", Value = "Pacific/Funafuti" },
            new SelectListItem { Text = "Pacific - Majuro (UTC + 12.0)", Value = "Pacific/Majuro" },
            new SelectListItem { Text = "Pacific - Wake (UTC +12.0)", Value = "Pacific/Wake" },
            new SelectListItem { Text = "Pacific - Wallis (UTC + 12.0)", Value = "Pacific/Wallis" },
            new SelectListItem { Text = "Pacific - Fiji (UTC + 12.0)", Value = "Pacific/Fiji" },
            new SelectListItem { Text = "Pacific - Tarawa (UTC + 12.0)", Value = "Pacific/Tarawa" },
            new SelectListItem { Text = "Pacific - Kwajalein (UTC + 12.0)", Value = "Pacific/Kwajalein" },
            new SelectListItem { Text = "Pacific - Norfolk (UTC + 12.0)", Value = "Pacific/Norfolk" },
            new SelectListItem { Text = "Pacific - Nauru (UTC + 12.0)", Value = "Pacific/Nauru" },
            new SelectListItem { Text = "Asia - Kamchatka (UTC + 12.0)", Value = "Asia/Kamchatka" },
            new SelectListItem { Text = "Asia - Anadyr (UTC + 12.0)", Value = "Asia/Anadyr" },
            new SelectListItem { Text = "Australia - ACT (UTC + 11.0)", Value = "Australia/ACT" },
            new SelectListItem { Text = "Australia - Canberra (UTC + 11.0)", Value = "Australia/Canberra" },
            new SelectListItem { Text = "Australia - Currie (UTC + 11.0)", Value = "Australia/Currie" },
            new SelectListItem { Text = "Australia - LHI (UTC + 11.0)", Value = "Australia/LHI" },
            new SelectListItem { Text = "Australia - NSW (UTC + 11.0)", Value = "Australia/NSW" },
            new SelectListItem { Text = "Australia - Tasmania (UTC + 11.0)", Value = "Australia/Tasmania" },
            new SelectListItem { Text = "Australia - Victoria (UTC + 11.0)", Value = "Australia/Victoria" },
            new SelectListItem { Text = "Pacific - Pohnpei (UTC + 11.0)", Value = "Pacific/Pohnpei" },
            new SelectListItem { Text = "Pacific - Ponape (UTC + 11.0)", Value = "Pacific/Ponape" },
            new SelectListItem { Text = "Antarctica - Casey (UTC + 11.0)", Value = "Antarctica/Casey" },
            new SelectListItem { Text = "Australia - Lord Howe (UTC + 11.0)", Value = "Australia/Lord Howe" },
            new SelectListItem { Text = "Antarctica - Macquarie (UTC + 11.0)", Value = "Antarctica/Macquarie" },
            new SelectListItem { Text = "Australia - Hobart (UTC + 11.0)", Value = "Australia/Hobart" },
            new SelectListItem { Text = "Australia - Melbourne (UTC + 11.0)", Value = "Australia/Melbourne" },
            new SelectListItem { Text = "Australia - Sydney (UTC + 11.0)", Value = "Australia/Sydney" },
            new SelectListItem { Text = "Pacific - Kosrae (UTC + 11.0)", Value = "Pacific/Kosrae" },
            new SelectListItem { Text = "Pacific - Guadalcanal (UTC + 11.0)", Value = "Pacific/Guadalcanal" },
            new SelectListItem { Text = "Pacific - Noumea (UTC + 11.0)", Value = "Pacific/Noumea" },
            new SelectListItem { Text = "Pacific - Bougainville (UTC + 11.0)", Value = "Pacific/Bougainville" },
            new SelectListItem { Text = "Asia - Magadan (UTC + 11.0)", Value = "Asia/Magadan" },
            new SelectListItem { Text = "Asia - Sakhalin (UTC + 11.0)", Value = "Asia/Sakhalin" },
            new SelectListItem { Text = "Asia - Srednekolymsk (UTC + 11.0)", Value = "Asia/Srednekolymsk" },
            new SelectListItem { Text = "Pacific - Efate (UTC + 11.0)", Value = "Pacific/Efate" },
            new SelectListItem { Text = "Australia - South (UTC + 10.5)", Value = "Australia/South" },
            new SelectListItem { Text = "Australia - Yancowinna (UTC + 10.5)", Value = "Australia/Yancowinna" },
            new SelectListItem { Text = "Australia - Broken Hill (UTC + 10.5)", Value = "Australia/Broken Hill" },
            new SelectListItem { Text = "Australia - Adelaide (UTC + 10.5)", Value = "Australia/Adelaide" },
            new SelectListItem { Text = "Antarctica - Dumont D’Urville (UTC + 10.0)", Value = "Antarctica/Dumont D’Urville" },
            new SelectListItem { Text = "Australia - Queensland (UTC + 10.0)", Value = "Australia/Queensland" },
            new SelectListItem { Text = "Pacific - Chuuk (UTC + 10.0)", Value = "Pacific/Chuuk" },
            new SelectListItem { Text = "Pacific - Saipan (UTC + 10.0)", Value = "Pacific/Saipan" },
            new SelectListItem { Text = "Pacific - Truk (UTC + 10.0)", Value = "Pacific/Truk" },
            new SelectListItem { Text = "Pacific - Yap (UTC + 10.0)", Value = "Pacific/Yap" },
            new SelectListItem { Text = "Pacific - Port Moresby (UTC + 10.0)", Value = "Pacific/Port Moresby" },
            new SelectListItem { Text = "Australia - Brisbane (UTC + 10.0)", Value = "Australia/Brisbane" },
            new SelectListItem { Text = "Australia - Lindeman (UTC + 10.0)", Value = "Australia/Lindeman" },
            new SelectListItem { Text = "Pacific - Guam (UTC + 10.0)", Value = "Pacific/Guam" },
            new SelectListItem { Text = "Asia - Vladivostok (UTC + 10.0)", Value = "Asia/Vladivostok" },
            new SelectListItem { Text = "Asia - Ust-Nera (UTC + 10.0)", Value = "Asia/Ust-Nera" },
            new SelectListItem { Text = "Australia - North (UTC + 9.5)", Value = "Australia/North" },
            new SelectListItem { Text = "Australia - Darwin (UTC + 9.5)", Value = "Australia/Darwin" },
            new SelectListItem { Text = "Japan (UTC + 9.0)", Value = "Japan" },
            new SelectListItem { Text = "Asia - Jayapura (UTC + 9.0)", Value = "Asia/Jayapura" },
            new SelectListItem { Text = "Asia - Tokyo (UTC + 9.0)", Value = "Asia/Tokyo" },
            new SelectListItem { Text = "Asia - Pyongyang (UTC + 9.0)", Value = "Asia/Pyongyang" },
            new SelectListItem { Text = "Asia - Seoul (UTC + 9.0)", Value = "Asia/Seoul" },
            new SelectListItem { Text = "Pacific - Palau (UTC + 9.0)", Value = "Pacific/Palau" },
            new SelectListItem { Text = "Asia - Chita (UTC + 9.0)", Value = "Asia/Chita" },
            new SelectListItem { Text = "Asia - Yakutsk (UTC + 9.0)", Value = "Asia/Yakutsk" },
            new SelectListItem { Text = "Asia - Khandyga (UTC + 9.0)", Value = "Asia/Khandyga" },
            new SelectListItem { Text = "Asia - Dili (UTC + 9.0)", Value = "Asia/Dili" },
            new SelectListItem { Text = "Australia - Eucla (UTC + 8.75)", Value = "Australia/Eucla" },
            new SelectListItem { Text = "Asia - Brunei (UTC + 8.0)", Value = "Asia/Brunei" },
            new SelectListItem { Text = "Asia - Chongqing (UTC + 8.0)", Value = "Asia/Chongqing" },
            new SelectListItem { Text = "Asia - Chungking (UTC + 8.0)", Value = "Asia/Chungking" },
            new SelectListItem { Text = "Asia - Harbin (UTC + 8.0)", Value = "Asia/Harbin" },
            new SelectListItem { Text = "Asia - Kuala Lumpur (UTC + 8.0)", Value = "Asia/Kuala Lumpur" },
            new SelectListItem { Text = "Asia - Macao (UTC + 8.0)", Value = "Asia/Macao" },
            new SelectListItem { Text = "Asia - Ujung Pandang (UTC + 8.0)", Value = "Asia/Ujung Pandang" },
            new SelectListItem { Text = "Asia - Ulan Bator (UTC + 8.0)", Value = "Asia/Ulan Bator" },
            new SelectListItem { Text = "Australia - West (UTC + 8.0)", Value = "Australia/West" },
            new SelectListItem { Text = "Hongkong (UTC + 8.0)", Value = "Hongkong" },
            new SelectListItem { Text = "Singapore (UTC + 8.0)", Value = "Singapore" },
            new SelectListItem { Text = "Australia - Perth (UTC + 8.0)", Value = "Australia/Perth" },
            new SelectListItem { Text = "Asia - Kuching (UTC + 8.0)", Value = "Asia/Kuching" },
            new SelectListItem { Text = "Asia - Shanghai (UTC + 8.0)", Value = "Asia/Shanghai" },
            new SelectListItem { Text = "Asia - Hong Kong (UTC + 8.0)", Value = "(Asia/Hong Kong" },
            new SelectListItem { Text = "Asia - Makassar (UTC + 8.0)", Value = "Asia/Makassar" },
            new SelectListItem { Text = "Asia - Ulaanbaatar (UTC + 8.0)", Value = "Asia/Ulaanbaatar" },
            new SelectListItem { Text = "Asia - Choibalsan (UTC + 8.0)", Value = "Asia/Choibalsan" },
            new SelectListItem { Text = "Asia - Macau (UTC + 8.0)", Value = "Asia/Macau" },
            new SelectListItem { Text = "Asia - Singapore (UTC + 8.0)", Value = "Asia/Singapore" },
            new SelectListItem { Text = "Asia - Manila (UTC + 8.0)", Value = "Asia/Manila" },
            new SelectListItem { Text = "Asia - Irkutsk (UTC + 8.0)", Value = "Asia/Irkutsk" },
            new SelectListItem { Text = "Asia - Taipei (UTC + 8.0)", Value = "Asia/Taipei" },
            new SelectListItem { Text = "Asia - Phnom Penh (UTC + 7.0)", Value = "Asia/Phnom Penh" },
            new SelectListItem { Text = "Asia - Saigon (UTC + 7.0)", Value = "Asia/Saigon" },
            new SelectListItem { Text = "Asia - Vientiane (UTC + 7.0)", Value = "Asia/Vientiane" },
            new SelectListItem { Text = "Indian - Christmas (UTC + 7.0)", Value = "Indian/Christmas" },
            new SelectListItem { Text = "Antarctica - Davis (UTC + 7.0)", Value = "Antarctica/Davis" },
            new SelectListItem { Text = "Asia - Bangkok (UTC +7.0)", Value = "Asia/Bangkok" },
            new SelectListItem { Text = "Asia - Jakarta (UTC + 7.0)", Value = "Asia/Jakarta" },
            new SelectListItem { Text = "Asia - Pontianak (UTC + 7.0)", Value = "Asia/Pontianak" },
            new SelectListItem { Text = "Asia - Hovd (UTC + 7.0)", Value = "Asia/Hovd" },
            new SelectListItem { Text = "Asia - Novosibirsk (UTC + 7.0)", Value = "Asia/Novosibirsk" },
            new SelectListItem { Text = "Asia - Barnaul (UTC + 7.0)", Value = "Asia/Barnaul" },
            new SelectListItem { Text = "Asia - Tomsk (UTC + 7.0)", Value = "Asia/Tomsk" },
            new SelectListItem { Text = "Asia - Novokuznetsk (UTC + 7.0)", Value = "Asia/Novokuznetsk" },
            new SelectListItem { Text = "Asia - Krasnoyarsk (UTC + 7.0)", Value = "Asia/Krasnoyarsk" },
            new SelectListItem { Text = "Asia - Ho Chi Minh (UTC + 7.0)", Value = "Asia/Ho Chi Minh" },
            new SelectListItem { Text = "Asia - Rangoon (UTC + 6.5)", Value = "Asia/Rangoon" },
            new SelectListItem { Text = "Indian - Cocos (UTC + 6.5)", Value = "Indian/Cocos" },
            new SelectListItem { Text = "Asia - Yangon (UTC + 6.5)", Value = "Asia/Yangon" },
            new SelectListItem { Text = "Antarctica - Vostok (UTC + 6.0)", Value = "Antarctica/Vostok" },
            new SelectListItem { Text = "Asia - Dacca (UTC + 6.0)", Value = "Asia/Dacca" },
            new SelectListItem { Text = "Asia - Kashgar (UTC + 6.0)", Value = "Asia/Kashgar" },
            new SelectListItem { Text = "Asia - Thimbu (UTC + 6.0)", Value = "Asia/Thimbu" },
            new SelectListItem { Text = "Asia - Urumqi (UTC + 6.0)", Value = "Asia/Urumqi" },
            new SelectListItem { Text = "Asia - Dhaka (UTC + 6.0)", Value = "Asia/Dhaka" },
            new SelectListItem { Text = "Asia - Thimphu (UTC + 6.0)", Value = "Asia/Thimphu" },
            new SelectListItem { Text = "Indian - Chagos (UTC + 6.0)", Value = "Indian/Chagos" },
            new SelectListItem { Text = "Asia - Bishkek (UTC + 6.0)", Value = "Asia/Bishkek" },
            new SelectListItem { Text = "Asia - Almaty (UTC +6.0)", Value = "Asia/Almaty" },
            new SelectListItem { Text = "Asia - Qostanay (UTC + 6.0)", Value = "Asia/Qostanay" },
            new SelectListItem { Text = "Asia - Omsk (UTC + 6.0)", Value = "Asia/Omsk" },
            new SelectListItem { Text = "Asia - Katmandu (UTC +5.75)", Value = "Asia/Katmandu" },
            new SelectListItem { Text = "Asia - Kathmandu (UTC + 5.75)", Value = "Asia/Kathmandu" },
            new SelectListItem { Text = "Asia - Calcutta (UTC + 5.5)", Value = "Asia/Calcutta" },
            new SelectListItem { Text = "Asia - Kolkata (UTC + 5.5)", Value = "Asia/Kolkata" },
            new SelectListItem { Text = "Asia - Colombo (UTC + 5.5)", Value = "Asia/Colombo" },
            new SelectListItem { Text = "Asia - Ashkhabad (UTC + 5.0)", Value = "Asia/Ashkhabad" },
            new SelectListItem { Text = "Indian - Kerguelen (UTC + 5.0)", Value = "Indian/Kerguelen" },
            new SelectListItem { Text = "Antarctica - Mawson (UTC + 5.0)", Value = "Antarctica/Mawson" },
            new SelectListItem { Text = "Asia - Qyzylorda (UTC + 5.0)", Value = "Asia/Qyzylorda" },
            new SelectListItem { Text = "Asia - Aqtobe (UTC + 5.0)", Value = "Asia/Aqtobe" },
            new SelectListItem { Text = "Asia - Aqtau (UTC + 5.0)", Value = "Asia/Aqtau" },
            new SelectListItem { Text = "Asia - Atyrau (UTC + 5.0)", Value = "Asia/Atyrau" },
            new SelectListItem { Text = "Asia - Oral (UTC + 5.0)", Value = "Asia/Oral" },
            new SelectListItem { Text = "Indian - Maldives (UTC + 5.0)", Value = "Indian/Maldives" },
            new SelectListItem { Text = "Asia - Karachi (UTC + 5.0)", Value = "Asia/Karachi" },
            new SelectListItem { Text = "Asia - Yekaterinburg (UTC + 5.0)", Value = "Asia/Yekaterinburg" },
            new SelectListItem { Text = "Asia - Dushanbe (UTC + 5.0)", Value = "Asia/Dushanbe" },
            new SelectListItem { Text = "Asia - Ashgabat (UTC + 5.0)", Value = "Asia/Ashgabat" },
            new SelectListItem { Text = "Asia - Samarkand (UTC + 5.0)", Value = "Asia/Samarkand" },
            new SelectListItem { Text = "Asia - Tashkent (UTC + 5.0)", Value = "Asia/Tashkent" },
            new SelectListItem { Text = "Asia - Kabul (UTC + 4.5)", Value = "Asia/Kabul" },
            new SelectListItem { Text = "Asia - Muscat (UTC + 4.0)", Value = "Asia/Muscat" },
            new SelectListItem { Text = "Indian - Mahe (UTC + 4.0)", Value = "Indian/Mahe" },
            new SelectListItem { Text = "Indian - Reunion (UTC + 4.0)", Value = "Indian/Reunion" },
            new SelectListItem { Text = "Asia - Dubai (UTC + 4.0)", Value = "Asia/Dubai" },
            new SelectListItem { Text = "Asia - Yerevan (UTC + 4.0)", Value = "Asia/Yerevan" },
            new SelectListItem { Text = "Asia - Baku (UTC + 4.0)", Value = "Asia/Baku" },
            new SelectListItem { Text = "Asia - Tbilisi (UTC + 4.0)", Value = "Asia/Tbilisi" },
            new SelectListItem { Text = "Indian - Mauritius (UTC + 4.0)", Value = "Indian/Mauritius" },
            new SelectListItem { Text = "Europe - Astrakhan (UTC + 4.0)", Value = "Europe/Astrakhan" },
            new SelectListItem { Text = "Europe - Saratov (UTC + 4.0)", Value = "Europe/Saratov" },
            new SelectListItem { Text = "Europe - Ulyanovsk (UTC + 4.0)", Value = "Europe/Ulyanovsk" },
            new SelectListItem { Text = "Europe - Samara (UTC + 4.0)", Value = "Europe/Samara" },
            new SelectListItem { Text = "Iran (UTC + 3.5)", Value = "Iran" },
            new SelectListItem { Text = "Asia - Tehran (UTC + 3.5)", Value = "Asia/Tehran" },
            new SelectListItem { Text = "Africa - Addis Ababa (UTC + 3.0)", Value = "Africa/Addis Ababa" },
            new SelectListItem { Text = "Africa - Asmara (UTC + 3.0)", Value = "Africa/Asmara" },
            new SelectListItem { Text = "Africa - Asmera (UTC + 3.0)", Value = "Africa/Asmera" },
            new SelectListItem { Text = "Africa - Dar es Salaam (UTC + 3.0)", Value = "Africa/Dar es Salaam" },
            new SelectListItem { Text = "Africa - Djibouti (UTC + 3.0)", Value = "Africa/Djibouti" },
            new SelectListItem { Text = "Africa - Kampala (UTC + 3.0)", Value = "Africa/Kampala" },
            new SelectListItem { Text = "Africa - Mogadishu (UTC + 3.0)", Value = "Africa/Mogadishu" },
            new SelectListItem { Text = "Antarctica - Syowa (UTC + 3.0)", Value = "Antarctica/Syowa" },
            new SelectListItem { Text = "Asia - Aden (UTC + 3.0)", Value = "Asia/Aden" },
            new SelectListItem { Text = "Asia - Bahrain (UTC + 3.0)", Value = "Asia/Bahrain" },
            new SelectListItem { Text = "Asia - Istanbul (UTC + 3.0)", Value = "Asia/Istanbul" },
            new SelectListItem { Text = "Asia - Kuwait (UTC + 3.0)", Value = "Asia/Kuwait" },
            new SelectListItem { Text = "Indian - Antananarivo (UTC + 3.0)", Value = "Indian/Antananarivo" },
            new SelectListItem { Text = "Indian - Comoro (UTC + 3.0)", Value = "Indian/Comoro" },
            new SelectListItem { Text = "Indian - Mayotte (UTC + 3.0)", Value = "Indian/Mayotte" },
            new SelectListItem { Text = "Turkey (UTC + 3.0)", Value = "Turkey" },
            new SelectListItem { Text = "Asia - Riyadh (UTC + 3.0)", Value = "(Asia/Riyadh" },
            new SelectListItem { Text = "Asia - Qatar (UTC + 3.0)", Value = "Asia/Qatar" },
            new SelectListItem { Text = "Europe - Minsk (UTC + 3.0)", Value = "Europe/Minsk" },
            new SelectListItem { Text = "Africa - Nairobi (UTC + 3.0)", Value = "Africa/Nairobi" },
            new SelectListItem { Text = "Asia - Baghdad (UTC + 3.0)", Value = "Asia/Baghdad" },
            new SelectListItem { Text = "Asia - Amman (UTC + 3.0)", Value = "(Asia/Amman" },
            new SelectListItem { Text = "Europe - Simferopol (UTC + 3.0)", Value = "Europe/Simferopol" },
            new SelectListItem { Text = "Europe - Kirov (UTC + 3.0)", Value = "Europe/Kirov" },
            new SelectListItem { Text = "Europe - Volgograd (UTC + 3.0)", Value = "Europe/Volgograd" },
            new SelectListItem { Text = "Asia - Damascus (UTC + 3.0)", Value = "Asia/Damascus" },
            new SelectListItem { Text = "Africa - Blantyre (UTC + 2.0)", Value = "Africa/Blantyre" },
            new SelectListItem { Text = "Africa - Bujumbura (UTC + 2.0)", Value = "Africa/Bujumbura" },
            new SelectListItem { Text = "Africa - Gaborone (UTC +2.0)", Value = "Africa/Gaborone" },
            new SelectListItem { Text = "Africa - Harare (UTC + 2.0)", Value = "Africa/Harare" },
            new SelectListItem { Text = "Africa - Kigali (UTC + 2.0)", Value = "Africa/Kigali" },
            new SelectListItem { Text = "Africa - Lubumbashi (UTC + 2.0)", Value = "Africa/Lubumbashi" },
            new SelectListItem { Text = "Africa - Lusaka (UTC + 2.0)", Value = "Africa/Lusaka" },
            new SelectListItem { Text = "Africa - Maseru (UTC + 2.0)", Value = "Africa/Maseru" },
            new SelectListItem { Text = "Africa - Mbabane (UTC + 2.0)", Value = "Africa/Mbabane" },
            new SelectListItem { Text = "Asia - Tel Aviv (UTC + 2.0)", Value = "Asia/Tel Aviv" },
            new SelectListItem { Text = "Egypt (UTC + 2.0)", Value = "Egypt" },
            new SelectListItem { Text = "Europe - Kiev (UTC + 2.0)", Value = "Europe/Kiev" },
            new SelectListItem { Text = "Europe - Mariehamn (UTC + 2.0)", Value = "Europe/Mariehamn" },
            new SelectListItem { Text = "Europe - Nicosia (UTC + 2.0)", Value = "Europe/Nicosia" },
            new SelectListItem { Text = "Europe - Tiraspol (UTC + 2.)", Value = "Europe/Tiraspol" },
            new SelectListItem { Text = "Europe - Uzhgorod (UTC + 2.0)", Value = "Europe/Uzhgorod" },
            new SelectListItem { Text = "Europe - Zaporozhye (UTC + 2.0)", Value = "Europe/Zaporozhye" },
            new SelectListItem { Text = "Israel (UTC + 2.0)", Value = "Israel" },
            new SelectListItem { Text = "Libya (UTC + 2.0)", Value = "Libya" },
            new SelectListItem { Text = "Europe - Sofia (UTC + 2.0)", Value = "Europe/Sofia" },
            new SelectListItem { Text = "Africa - Maputo (UTC + 2.0)", Value = "Africa/Maputo" },
            new SelectListItem { Text = "Asia - Nicosia (UTC + 2.0)", Value = "Asia/Nicosia" },
            new SelectListItem { Text = "Asia - Famagusta (UTC + 2.0)", Value = "Asia/Famagusta" },
            new SelectListItem { Text = "Europe - Tallinn (UTC + 2.0)", Value = "Europe/Tallinn" },
            new SelectListItem { Text = "Africa - Cairo (UTC + 2.0)", Value = "Africa/Cairo" },
            new SelectListItem { Text = "Asia - Jerusalem (UTC + 2.0)", Value = "Asia/Jerusalem" },
            new SelectListItem { Text = "Asia - Beirut (UTC + 2.0)", Value = "Asia/Beirut" },
            new SelectListItem { Text = "Africa - Johannesburg (UTC + 2.0)", Value = "Africa/Johannesburg" },
            new SelectListItem { Text = "Europe - Vilnius (UTC + 2.0)", Value = "Europe/Vilnius" },
            new SelectListItem { Text = "Europe - Riga (UTC + 2.0)", Value = "Europe/Riga" },
            new SelectListItem { Text = "Africa - Tripoli (UTC + 2.0)", Value = "Africa/Tripoli" },
            new SelectListItem { Text = "Europe - Chisinau (UTC + 2.0)", Value = "Europe/Chisinau" },
            new SelectListItem { Text = "Africa - Windhoek (UTC + 2.0)", Value = "Africa/Windhoek" },
            new SelectListItem { Text = "Asia - Gaza (UTC + 2.0)", Value = "Asia/Gaza" },
            new SelectListItem { Text = "Asia - Hebron (UTC + 2.0)", Value = "Asia/Hebron" },
            new SelectListItem { Text = "Europe - Bucharest (UTC + 2.0)", Value = "Europe/Bucharest" },
            new SelectListItem { Text = "Europe - Kaliningrad (UTC + 2.0)", Value = "Europe/Kaliningrad" },
            new SelectListItem { Text = "Africa - Khartoum (UTC + 2.0)", Value = "Africa/Khartoum" },
            new SelectListItem { Text = "Africa - Juba (UTC + 2.0)", Value = "Africa/Juba" },
            new SelectListItem { Text = "Europe - Kyiv (UTC + 2.0)", Value = "Europe/Kyiv" },
            new SelectListItem { Text = "Africa - Bangui (UTC + 1.0)", Value = "Africa/Bangui" },
            new SelectListItem { Text = "Africa - Brazzaville (UTC + 1.0)", Value = "Africa/Brazzaville" },
            new SelectListItem { Text = "Africa - Douala (UTC + 1.0)", Value = "Africa/Douala" },
            new SelectListItem { Text = "Africa - Kinshasa (UTC + 1.0)", Value = "Africa/Kinshasa" },
            new SelectListItem { Text = "Africa - Libreville (UTC + 1.0)", Value = "Africa/Libreville" },
            new SelectListItem { Text = "Africa - Luanda (UTC + 1.0)", Value = "Africa/Luanda" },
            new SelectListItem { Text = "Africa - Malabo (UTC + 1.0)", Value = "Africa/Malabo" },
            new SelectListItem { Text = "Africa - Niamey (UTC + 1.0)", Value = "Africa/Niamey" },
            new SelectListItem { Text = "Africa - Porto-Novo (UTC + 1.0)", Value = "Africa/Porto-Novo" },
            new SelectListItem { Text = "Arctic - Longyearbyen (UTC + 1.0)", Value = "Arctic/Longyearbyen" },
            new SelectListItem { Text = "Atlantic - Jan Mayen (UTC + 1.0)", Value = "Atlantic/Jan Mayen" },
            new SelectListItem { Text = "Europe - Bratislava (UTC + 1.0)", Value = "Europe/Bratislava" },
            new SelectListItem { Text = "Europe - Busingen (UTC + 1.0)", Value = "Europe/Busingen" },
            new SelectListItem { Text = "Europe - Copenhagen (UTC + 1.0)", Value = "Europe/Copenhagen" },
            new SelectListItem { Text = "Europe - Ljubljana (UTC + 1.0)", Value = "Europe/Ljubljana" },
            new SelectListItem { Text = "Europe - Luxembourg (UTC + 1.0)", Value = "Europe/Luxembourg" },
            new SelectListItem { Text = "Europe - Monaco (UTC + 1.0)", Value = "Europe/Monaco" },
            new SelectListItem { Text = "Europe - Oslo (UTC + 1.0)", Value = "Europe/Oslo" },
            new SelectListItem { Text = "Europe - Podgorica (UTC + 1.0)", Value = "Europe/Podgorica" },
            new SelectListItem { Text = "Europe - San Marino (UTC + 1.0)", Value = "Europe/San Marino" },
            new SelectListItem { Text = "Europe - Sarajevo (UTC + 1.0)", Value = "Europe/Sarajevo" },
            new SelectListItem { Text = "Europe - Skopje (UTC + 1.0)", Value = "Europe/Skopje" },
            new SelectListItem { Text = "Europe - Stockholm (UTC + 1.0)", Value = "Europe/Stockholm" },
            new SelectListItem { Text = "Europe - Vaduz (UTC + 1.0)", Value = "Europe/Vaduz" },
            new SelectListItem { Text = "Europe - Vatican (UTC + 1.0)", Value = "Europe/Vatican" },
            new SelectListItem { Text = "Europe - Zagreb (UTC + 1.0)", Value = "Europe/Zagreb" },
            new SelectListItem { Text = "Poland (UTC + 1.0)", Value = "Poland" },
            new SelectListItem { Text = "Europe - Andorra (UTC + 1.0)", Value = "Europe/Andorra" },
            new SelectListItem { Text = "Europe - Tirane (UTC + 1.0)", Value = "Europe/Tirane" },
            new SelectListItem { Text = "Africa - Lagos (UTC + 1.0)", Value = "Africa/Lagos" },
            new SelectListItem { Text = "Europe - Belgrade (UTC + 1.0)", Value = "Europe/Belgrade" },
            new SelectListItem { Text = "Africa - Algiers (UTC + 1.0)", Value = "Africa/Algiers" },
            new SelectListItem { Text = "Africa - El Aaiun (UTC + 1.0)", Value = "Africa/El Aaiun" },
            new SelectListItem { Text = "Africa - Ceuta (UTC + 1.0)", Value = "Africa/Ceuta" },
            new SelectListItem { Text = "Europe - Gibraltar (UTC + 1.0)", Value = "Europe/Gibraltar" },
            new SelectListItem { Text = "Africa - Casablanca (UTC + 1.0)", Value = "Africa/Casablanca" },
            new SelectListItem { Text = "Europe - Malta (UTC + 1.0)", Value = "Europe/Malta" },
            new SelectListItem { Text = "Africa - Ndjamena (UTC + 1.0)", Value = "Africa/Ndjamena" },
            new SelectListItem { Text = "Africa - Tunis (UTC + 1.0)", Value = "Africa/Tunis" },
            new SelectListItem { Text = "Africa - Accra (UTC + 0.0)", Value = "Africa/Accra" },
            new SelectListItem { Text = "Africa - Bamako (UTC + 0.0)", Value = "Africa/Bamako" },
            new SelectListItem { Text = "Africa - Banjul (UTC + 0.0)", Value = "Africa/Banjul" },
            new SelectListItem { Text = "Africa - Conakry (UTC + 0.0)", Value = "Africa/Conakry" },
            new SelectListItem { Text = "Africa - Dakar (UTC + 0.0)", Value = "Africa/Dakar" },
            new SelectListItem { Text = "Africa - Freetown (UTC + 0.0)", Value = "Africa/Freetown" },
            new SelectListItem { Text = "Africa - Lome (UTC + 0.0)", Value = "Africa/Lome" },
            new SelectListItem { Text = "Africa - Nouakchott (UTC + 0.0)", Value = "Africa/Nouakchott" },
            new SelectListItem { Text = "Africa - Ouagadougou (UTC + 0.0)", Value = "Africa/Ouagadougou" },
            new SelectListItem { Text = "Africa - Timbuktu (UCT + 0.0)", Value = "Africa/Timbuktu" },
            new SelectListItem { Text = "Atlantic - Faeroe (UTC + 0.0)", Value = "Atlantic/Faeroe" },
            new SelectListItem { Text = "Atlantic - Reykjavik (UTC + 0.0)", Value = "Atlantic/Reykjavik" },
            new SelectListItem { Text = "Atlantic - St Helena (UTC + 0.0)", Value = "Atlantic/St Helena" },
            new SelectListItem { Text = "Europe - Belfast (UTC + 0.0)", Value = "Europe/Belfast" },
            new SelectListItem { Text = "Europe - Guernsey (UTC + 0.0)", Value = "Europe/Guernsey" },
            new SelectListItem { Text = "Europe - Isle of Man (UTC + 0.0)", Value = "Europe/Isle of Man" },
            new SelectListItem { Text = "Europe - Jersey (UTC + 0.0)", Value = "Europe/Jersey" },
            new SelectListItem { Text = "Greenwich (UTC + 0.0)", Value = "Greenwich" },
            new SelectListItem { Text = "Iceland (UTC + 0.0)", Value = "Iceland" },
            new SelectListItem { Text = "Portugal (UTC + 0.0)", Value = "Portugal" },
            new SelectListItem { Text = "Antarctica - Troll UTC + 0.0}", Value = "Antarctica/Troll" },
            new SelectListItem { Text = "Africa - Abidjan (UTC + 0.0)", Value = "Africa/Abidjan" },
            new SelectListItem { Text = "Atlantic - Canary (UTC + 0.0)", Value = "Atlantic/Canary" },
            new SelectListItem { Text = "America - Danmarkshavn (UTC + 0.0)", Value = "America/Danmarkshavn" },
            new SelectListItem { Text = "Africa - Bissau (UTC + 0.0)", Value = "Africa/Bissau" },
            new SelectListItem { Text = "Africa - Monrovia (UTC + 0.0)", Value = "Africa/Monrovia" },
            new SelectListItem { Text = "Atlantic - Madeira (UTC + 0.0)", Value = "Atlantic/Madeira" },
            new SelectListItem { Text = "Africa - Sao Tome (UTC + 0.0)", Value = "Africa/Sao Tome" },
            new SelectListItem { Text = "Atlantic - Cape Verde (UTC - 1.0)", Value = "Atlantic/Cape Verde" },
            new SelectListItem { Text = "America - Scoresbysund (UTC - 1)", Value = "America/Scoresbysund" },
            new SelectListItem { Text = "Atlantic - Azores (UTC - 1.0)", Value = "Atlantic/Azores" },
            new SelectListItem { Text = "America - Godthab (UTC - 2.0)", Value = "America/Godthab" },
            new SelectListItem { Text = "Brazil - De Noronha (UTC - 2.0)", Value = "Brazil/De Noronha" },
            new SelectListItem { Text = "America - Noronha (UTC - 2.0)", Value = "America/Noronha" },
            new SelectListItem { Text = "America - Nuuk (UTC - 2.0)", Value = "America/Nuuk" },
            new SelectListItem { Text = "Atlantic - South Georgia (UTC - 2.0)", Value = "Atlantic/South Georgia" },
            new SelectListItem { Text = "America - Comod Rivadavia (UTC - 3.0)", Value = "America/Comod Rivadavia" },
            new SelectListItem { Text = "America - Buenos Aires (UTC - 3.0)", Value = "America/Buenos Aires" },
            new SelectListItem { Text = "America - Catamarca (UTC - 3.0)", Value = "America/Catamarca" },
            new SelectListItem { Text = "America - Cordoba (UTC - 3.0)", Value = "America/Cordoba" },
            new SelectListItem { Text = "America - Jujuy (UTC - 3.0)", Value = "America/Jujuy" },
            new SelectListItem { Text = "America - Mendoza (UTC - 3.0)", Value = "America/Mendoza" },
            new SelectListItem { Text = "America - Rosario (UTC - 3.0)", Value = "America/Rosario" },
            new SelectListItem { Text = "Brazil - East (UTC - 3.0)", Value = "Brazil/East" },
            new SelectListItem { Text = "Antarctica - Palmer (UTC - 3.0)", Value = "Antarctica/Palmer" },
            new SelectListItem { Text = "Antarctica - Rothera (UTC - 3.0)", Value = "Antarctica/Rothera" },
            new SelectListItem { Text = "America - Salta (UTC - 3.0)", Value = "America/Salta" },
            new SelectListItem { Text = "America - Tucuman (UTC - 3.0)", Value = "America/Tucuman" },
            new SelectListItem { Text = "America - La Rioja (UTC - 3.0)", Value = "America/La Rioja" },
            new SelectListItem { Text = "America - San Juan  (UTC - 3.0)", Value = "America/San Juan" },
            new SelectListItem { Text = "America - San Luis (UTC - 3.0)", Value = "America/San Luis" },
            new SelectListItem { Text = "America - Rio Gallegos (UTC - 3.0)", Value = "America/Rio Gallegos" },
            new SelectListItem { Text = "America - Ushuaia (UTC - 3.0)", Value = "America/Ushuaia" },
            new SelectListItem { Text = "America - Belem (UTC - 3.0)", Value = "America/Belem" },
            new SelectListItem { Text = "America - Fortaleza (UTC - 3.0)", Value = "America/Fortaleza" },
            new SelectListItem { Text = "America - Recife (UTC - 3.0)", Value = "America/Recife" },
            new SelectListItem { Text = "America - Araguaina (UTC - 3.0)", Value = "America/Araguaina" },
            new SelectListItem { Text = "America - Maceio (UTC - 3.0)", Value = "America/Maceio" },
            new SelectListItem { Text = "America - Bahia (UTC - 3.0)", Value = "America/Bahia" },
            new SelectListItem { Text = "America - Santarem (UTC - 3.0)", Value = "America/Santarem" },
            new SelectListItem { Text = "America - Santiago (UTC - 3.0)", Value = "America/Santiago" },
            new SelectListItem { Text = "America - Punta Arenas (UTC - 3.0)", Value = "America/Punta Arenas" },
            new SelectListItem { Text = "Atlantic - Stanley (UTC - 3.0)", Value = "Atlantic/Stanley" },
            new SelectListItem { Text = "America - Cayenne (UTC - 3.0)", Value = "America/Cayenne" },
            new SelectListItem { Text = "America - Miquelon (UTC - 3.0)", Value = "America/Miquelon" },
            new SelectListItem { Text = "America - Asuncion (UTC - 3.0)", Value = "America/Asuncion" },
            new SelectListItem { Text = "America - Paramaribo (UTC - 3.0)", Value = "America/Paramaribo" },
            new SelectListItem { Text = "America - Montevideo (UTC - 3.0)", Value = "America/Montevideo" },
            new SelectListItem { Text = "America - St Johns (UTC - 3.5)", Value = "America/St Johns" },
            new SelectListItem { Text = "America - Anguilla (UTC - 4.0)", Value = "America/Anguilla" },
            new SelectListItem { Text = "America - Antiqua (UTC - 4.0)", Value = "America/Antigua" },
            new SelectListItem { Text = "America - Aruba (UCT - 4.0)", Value = "America/Aruba" },
            new SelectListItem { Text = "America - Blanc-Sablon (UTC - 4.0)", Value = "America/Blanc-Sablon" },
            new SelectListItem { Text = "America - Curacao (UTC - 4.0)", Value = "America/Curacao" },
            new SelectListItem { Text = "America - Dominica (UTC - 4.0)", Value = "America/Dominica" },
            new SelectListItem { Text = "America - Grenada (UTC - 4.0)", Value = "America/Grenada" },
            new SelectListItem { Text = "America - Guadeloupe (UTC -4.0)", Value = "America/Guadeloupe" },
            new SelectListItem { Text = "America - Kralendijk (UTC - 4.0)", Value = "America/Kralendijk" },
            new SelectListItem { Text = "America - Lower Princes (UTC - 4.0)", Value = "America/Lower Princes" },
            new SelectListItem { Text = "America - Marigot (UTC - 4.0)", Value = "America/Marigot" },
            new SelectListItem { Text = "America - Montserrat (UTC - 4.0)", Value = "America/Montserrat" },
            new SelectListItem { Text = "America - Port of Spain (UTC - 4.0)", Value = "America/Port of Spain" },
            new SelectListItem { Text = "America - St Barthelemy (UTC - 4.0)", Value = "America/St Barthelemy" },
            new SelectListItem { Text = "America - St Kitts (UTC - 4.0)", Value = "America/St Kitts" },
            new SelectListItem { Text = "America - St Lucia (UTC - 4.0)", Value = "America/St Lucia" },
            new SelectListItem { Text = "America - St Thomas (UTC - 4.0)", Value = "America/St Thomas" },
            new SelectListItem { Text = "America - St Vincent (UTC - 4.0)", Value = "America/St Vincent" },
            new SelectListItem { Text = "America - Tortola (UTC - 4.0)", Value = "America/Tortola" },
            new SelectListItem { Text = "America - Virgin (UTC - 4.0)", Value = "America/Virgin" },
            new SelectListItem { Text = "Brazil - West (UTC - 4.0)", Value = "Brazil/West" },
            new SelectListItem { Text = "America - Puerto Rico (UTC - 4.0)", Value = "America/Puerto Rico" },
            new SelectListItem { Text = "America - Barbados (UTC - 4.0)", Value = "America/Barbados" },
            new SelectListItem { Text = "Atlantic - Bermuda (UTC - 4.0)", Value = "America/Bermuda" },
            new SelectListItem { Text = "America - La Paz (UTC - 4.0)", Value = "America/La Paz" },
            new SelectListItem { Text = "America - Campo Grande (UTC - 4.0)", Value = "America/Campo Grande" },
            new SelectListItem { Text = "America - Cuiaba (UTC - 4.0)", Value = "America/Cuiaba" },
            new SelectListItem { Text = "America - Porto Velho (UTC - 4.0)", Value = "America/Porto Velho" },
            new SelectListItem { Text = "America - Boa Vista (UTC - 4.0)", Value = "America/Boa Vista" },
            new SelectListItem { Text = "America - Manaus (UTC - 4.0)", Value = "America/Manaus" },
            new SelectListItem { Text = "America - Halifax (UTC - 4.0)", Value = "America/Halifax" },
            new SelectListItem { Text = "America - Glace Bay (UTC - 4.0)", Value = "America/Glace Bay" },
            new SelectListItem { Text = "America - Moncton (UTC - 4.0)", Value = "America/Moncton" },
            new SelectListItem { Text = "America - Goose Bay (UTC - 4.0)", Value = "America/Goose Bay" },
            new SelectListItem { Text = "America - Santo Domingo (UTC - 4.0)", Value = "America/Santo Domingo" },
            new SelectListItem { Text = "America - Thule (UTC - 4.0)", Value = "America/Thule" },
            new SelectListItem { Text = "America - Guyana (UTC -4.0)", Value = "America/Guyana" },
            new SelectListItem { Text = "America - Martinique (UTC - 4.0)", Value = "America/Martinique" },
            new SelectListItem { Text = "America - Caracas (UTC - 4.0)", Value = "America/Caracas" },
            new SelectListItem { Text = "America - Atikokan (UTC - 5.0)", Value = "(America/Atikokan" },
            new SelectListItem { Text = "America - Cayman (UTC - 5.0)", Value = "America/Cayman" },
            new SelectListItem { Text = "America - Coral Harbour (UTC - 5.0)", Value = "America/Coral Harbour" },
            new SelectListItem { Text = "America - Fort Wayne (UTC - 5.0)", Value = "America/Fort Wayne" },
            new SelectListItem { Text = "America - Indianapolis (UTC - 5.0)", Value = "America/Indianapolis" },
            new SelectListItem { Text = "America - Louisville (UTC - 5.0)", Value = "America/Louisville" },
            new SelectListItem { Text = "America - Montreal (UTC - 5.0)", Value = "America/Montreal" },
            new SelectListItem { Text = "America - Nassau (UTC - 5.0)", Value = "America/Nassau" },
            new SelectListItem { Text = "America - Nipigon (UTC - 5.0)", Value = "America/Nipigon" },
            new SelectListItem { Text = "America - Pangnirtung (UTC - 5.0)", Value = "America/Pangnirtung" },
            new SelectListItem { Text = "America - Porto Acre (UTC - 5.0)", Value = "America/Porto Acre" },
            new SelectListItem { Text = "America - Thunder Bay (UTC - 5.0)", Value = "America/Thunder Bay" },
            new SelectListItem { Text = "Brazil - Acre (UTC - 5.0)", Value = "Brazil/Acre" },
            new SelectListItem { Text = "Chile - Easter Island (UTC - 5.0)", Value = "Chile/Easter Island" },
            new SelectListItem { Text = "Cuba ( UTC - 5.0)", Value = "Cuba" },
            new SelectListItem { Text = "Jamaica (UTC - 5.0)", Value = "Jamaica" },
            new SelectListItem { Text = "America - East-Indiana (UTC - 5.0)", Value = "America/East-Indiana" },
            new SelectListItem { Text = "America - Michigan (UTC - 5.0)", Value = "America/Michigan" },
            new SelectListItem { Text = "America - Eirunepe (UTC - 5.0)", Value = "America/Eirunepe" },
            new SelectListItem { Text = "America - Rio Branco (UTC - 5.0)", Value = "America/Rio Branco" },
            new SelectListItem { Text = "America - Toronto (UTC - 5.0)", Value = "America/Toronto" },
            new SelectListItem { Text = "America - Iqaluit (UTC - 5.0)", Value = "America/Iqaluit" },
            new SelectListItem { Text = "America - Panama (UTC - 5.0)", Value = "America/Panama" },
            new SelectListItem { Text = "Pacific - Easter (UTC - 5.0)", Value = "Pacific/Easter" },
            new SelectListItem { Text = "America - Bogota (UTC - 5.0)", Value = "America/Bogota" },
            new SelectListItem { Text = "America - Havana (UTC - 5.0)", Value = "America/Havana" },
            new SelectListItem { Text = "America - Guayaquil (UTC - 5.0)", Value = "America/Guayaquil" },
            new SelectListItem { Text = "America - Port-au-Prince (UTC - 5.0)", Value = "America/Port-au-Prince" },
            new SelectListItem { Text = "America - Jamaica (UTC - 5.0)", Value = "America/Jamaica" },
            new SelectListItem { Text = "America - Cancun (UTC - 5.0)", Value = "America/Cancun" },
            new SelectListItem { Text = "America - Lima (UTC - 5.0)", Value = "America/Lima" },
            new SelectListItem { Text = "America - Grand Turk (UTC - 5.0)", Value = "America/Grand Turk" },
            new SelectListItem { Text = "America - New York (UTC - 5.0)", Value = "America/New York" },
            new SelectListItem { Text = "America - Detroit (UTC - 5.0)", Value = "America/Detroit" },
            new SelectListItem { Text = "America - Monticello (UTC - 5.0)", Value = "America/Monticello" },
            new SelectListItem { Text = "America - Indianapolis (UTC - 5.0)", Value = "America/Indianapolis" },
            new SelectListItem { Text = "America - Vincennes (UTC - 5.0)", Value = "America/Vincennes" },
            new SelectListItem { Text = "America - Winamac (UTC - 5.0)", Value = "America/Winamac" },
            new SelectListItem { Text = "America - Marengo (UTC - 5.0)", Value = "America/Marengo" },
            new SelectListItem { Text = "America - Petersburg (UTC - 5.0)", Value = "America/Petersburg" },
            new SelectListItem { Text = "America - Vevay (UTC - 5.0)", Value = "America/Vevay" },
            new SelectListItem { Text = "America - Knox (UTC - 6.0)", Value = "America/Knox" },
            new SelectListItem { Text = "America - Rainy River (UTC - 6.0)", Value = "America/Rainy River" },
            new SelectListItem { Text = "Mexico - General (UTC - 6.0)", Value = "Mexico/General" },
            new SelectListItem { Text = "America - Belize (UTC - 6.0)", Value = "America/Belize" },
            new SelectListItem { Text = "America - Winnipeg (UTC - 6.0)", Value = "America/Winnipeg" },
            new SelectListItem { Text = "America - Resolute (UTC - 6.0)", Value = "America/Resolute" },
            new SelectListItem { Text = "America - Rankin Inlet (UTC - 6.0)", Value = "America/Rankin Inlet" },
            new SelectListItem { Text = "America - Regina (UTC - 6.0)", Value = "America/Regina" },
            new SelectListItem { Text = "America - Swift Current (UTC - 6.0)", Value = "America/Swift Current" },
            new SelectListItem { Text = "America - Costa Rica (UCT - 6.0)", Value = "America/Costa Rica" },
            new SelectListItem { Text = "Pacific - Galapagos (UTC - 6.0)", Value = "Pacific/Galapagos" },
            new SelectListItem { Text = "America - Guatemala (UTC - 6.0)", Value = "America/Guatemala" },
            new SelectListItem { Text = "America - Tegucigalpa (UTC - 6.0)", Value = "America/Tegucigalpa" },
            new SelectListItem { Text = "America - Mexico City (UTC - 6.0)", Value = "America/Mexico City" },
            new SelectListItem { Text = "America - Merida (UTC - 6.0)", Value = "America/Merida" },
            new SelectListItem { Text = "America - Monterrey (UTC - 6.0)", Value = "America/Monterrey" },
            new SelectListItem { Text = "America - Matamoros (UTC - 6.0)", Value = "America/Matamoros" },
            new SelectListItem { Text = "America - Chihuahua (UTC - 6.0)", Value = "America/Chihuahua" },
            new SelectListItem { Text = "America - Ojinaga (UTC - 6.0)", Value = "America/Ojinaga" },
            new SelectListItem { Text = "America - Bahia Banderas (UTC - 6.0)", Value = "America/Bahia Banderas" },
            new SelectListItem { Text = "America - Managua (UTC - 6.0)", Value = "America/Managua" },
            new SelectListItem { Text = "America - El Salvador (UTC - 6.0)", Value = "America/El Salvador" },
            new SelectListItem { Text = "America - Chicago (UTC - 6.0)", Value = "America/Chicago" },
            new SelectListItem { Text = "America - Tell City (UTC - 6.0)", Value = "America/Tell City" },
            new SelectListItem { Text = "America - Menominee (UTC - 6.0)", Value = "America/Menominee" },
            new SelectListItem { Text = "America - Center (UTC - 6.0)", Value = "America/Center" },
            new SelectListItem { Text = "America - New Salem (UTC - 6.0)", Value = "America/New Salem" },
            new SelectListItem { Text = "America - Beulah (UTC - 6.0)", Value = "America/Beulah" },
            new SelectListItem { Text = "America - Creston (UTC - 7.0)", Value = "America/Creston" },
            new SelectListItem { Text = "America - Shiprock (UTC - 7.0)", Value = "America/Shiprock" },
            new SelectListItem { Text = "America - Yellowknife (UTC - 7.0)", Value = "America/Yellowknife" },
            new SelectListItem { Text = "Mexico - Baja Sur (UTC - 7.0)", Value = "Mexico/Baja Sur" },
            new SelectListItem { Text = "Navajo (UTC - 7.0)", Value = "Navajo" },
            new SelectListItem { Text = "America - Edmonton (UTC - 7.0)", Value = "America - Edmonton" },
            new SelectListItem { Text = "America - Cambridge Bay (UTC - 7.0)", Value = "America/Cambridge Bay" },
            new SelectListItem { Text = "America - Inuvik (UTC - 7.0)", Value = "America/Inuvik" },
            new SelectListItem { Text = "America - Dawson Creek (UTC - 7.0)", Value = "America/Dawson Creek" },
            new SelectListItem { Text = "America - Fort Nelson (UTC - 7.0)", Value = "America/Fort Nelson" },
            new SelectListItem { Text = "America - Whitehorse (UTC - 7.0)", Value = "America/Whitehorse" },
            new SelectListItem { Text = "America - Dawson (UTC - 7.0)", Value = "America/Dawson" },
            new SelectListItem { Text = "America - Phoenix (UTC - 7.0)", Value = "America/Phoenix" },
            new SelectListItem { Text = "America - Ciudad Juarez (UTC - 7.0)", Value = "America/Ciudad Juarez" },
            new SelectListItem { Text = "America - Mazatlan (UTC - 7.0)", Value = "America/Mazatlan" },
            new SelectListItem { Text = "America - Hermosillo (UTC - 7.0)", Value = "America/Hermosillo" },
            new SelectListItem { Text = "America - Denver (UTC - 7.0)", Value = "America/Denver" },
            new SelectListItem { Text = "America - Boise (UTC - 7.0)", Value = "America/Boise" },
            new SelectListItem { Text = "America - Ensenada (UTC 7.0)", Value = "America/Ensenada" },
            new SelectListItem { Text = "America - Santa Isabel (UTC - 8.0)", Value = "America/Santa Isabel" },
            new SelectListItem { Text = "Mexico - Baja Norte (UTC - 8.0)", Value = "Mexico/Baja Norte" },
            new SelectListItem { Text = "America - Vancouver (UTC - 8.0)", Value = "America/Vancouver" },
            new SelectListItem { Text = "America - Tijuana (UTC - 8.0)", Value = "America/Tijuana" },
            new SelectListItem { Text = "Pacific - Pitcairn (UTC - 8.0)", Value = "Pacific/Pitcairn" },
            new SelectListItem { Text = "America - Los Angeles (UTC - 8.0)", Value = "America/Los Angeles" },
            new SelectListItem { Text = "Pacific - Gambier (UTC - 9.0)", Value = "Pacific/Gambier" },
            new SelectListItem { Text = "America - Anchorage (UTC - 9.0)", Value = "America/Anchorage" },
            new SelectListItem { Text = "America - Juneau (UTC - 9.0)", Value = "America/Juneau" },
            new SelectListItem { Text = "America - Sitka (UTC - 9.0)", Value = "America/Sitka" },
            new SelectListItem { Text = "America - Metlakatla (UTC - 9.0)", Value = "America/Metlakatla}" },
            new SelectListItem { Text = "America - Yakutat (UTC - 9.0)", Value = "America/Yakutat" },
            new SelectListItem { Text = "America - Nome (UTC - 9.0)", Value = "America/Nome" },
            new SelectListItem { Text = "Pacific - Marquesas (UTC - 9.5)", Value = "Pacific/Marquesas" },
            new SelectListItem { Text = "America - Atka (UTC - 10.0)", Value = "America/Atka" },
            new SelectListItem { Text = "Pacific - Johnston (UTC - 10.0)", Value = "Pacific/Johnston" },
            new SelectListItem { Text = "Pacific - Rarotonga (UTC - 10.0", Value = "Pacific/Rarotonga" },
            new SelectListItem { Text = "Pacific - Tahiti (UTC - 10.0)", Value = "Pacific/Tahiti" },
            new SelectListItem { Text = "America - Adak (UTC - 10.0)", Value = "America/Adak" },
            new SelectListItem { Text = "Pacific - Honolulu (UTC - 10.0)", Value = "Pacific/Honolulu" },
            new SelectListItem { Text = "Pacific - Midway (UTC - 11.0)", Value = "Pacific/Midway" },
            new SelectListItem { Text = "Pacific - Samoa (UTC - 11.0)", Value = "Pacific/Samoa" },
            new SelectListItem { Text = "Pacific - Pago Pago (UTC - 11.0)", Value = "Pacific/Pago Pago" },
            new SelectListItem { Text = "Pacific - Niue (UTC - 11.0)", Value = "Pacific/Niue" },
        };
    }
}
